### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qiuxiaojian** [zhaodahai/wx-image-compress#1]
尝试了一些这个组件的使用，发现老出现报错，发现也没有太多的说明文档。
虽然组件不复杂，可是建议提供一个例子，可能会更加的易懂

**Comment by qiuxiaojian** [comment]
经过苦苦挣扎  还是放弃使用  自己写了

**Comment by zhaodahai** [comment]
嗯。仅供参考。。。
 https://www.jianshu.com/p/24f47e9c1794

**Comment by wowenwen** [comment]
thirdScriptError
_.getImageFileInfo is not a function; [Component] Event Listener Error @ miniprogram_npm/@vant/weapp/button/index#(anonymous)
TypeError: _.getImageFileInfo is not a function

**Comment by wowenwen** [comment]
TypeError: _.getImageFileInfo is not a function
    at ImgCompress.drawCanvas (http://127.0.0.1:48566/appservice/utils/wx-image-compress/img-compress.js:71:16)
    at ImgCompress.compress (http://127.0.0.1:48566/appservice/utils/wx-image-compress/img-compress.js:34:24)
    at Se.send (http://127.0.0.1:48566/appservice/pages/photo/photo.js:129:22)
